### ISSUE TITLE
Slinky prices do not work on devnet

### ISSUE THREAD

**Issue by alex-nax** [warden-protocol/wardenprotocol#821]

**Comment by jlehtimaki** [comment]
Hello @alex-nax ,

When reporting an issue, please be more specific what is not working and how are you determining it's not working.
By the looks of it, the price data is on chain:
```
root@devnet-validator-0-0:/# wardend q oracle currency-pairs
currency_pairs:
- Base: AAVE
  Quote: USD
- Base: ADA
  Quote: USD
- Base: ATOM
  Quote: USD
- Base: BTC
  Quote: USD
- Base: ETH
  Quote: USD
- Base: USDT
  Quote: USD
root@devnet-validator-0-0:/# wardend q oracle price AAVE USD
decimals: "8"
id: "0"
nonce: "47601"
price:
  block_height: "47610"
  block_timestamp: "2024-09-16T09:34:30.961777171Z"
  price: "14157415741"
root@devnet-validator-0-0:/# wardend q oracle price ATOM USD
decimals: "9"
id: "2"
nonce: "47602"
price:
  block_height: "47611"
  block_timestamp: "2024-09-16T09:34:36.393721087Z"
  price: "4012401240"
```
